# Generated by Django 3.2.18 on 2023-04-09 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_auto_20230409_1859'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_message', models.TextField(verbose_name='текст сообщения')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='время публикации')),
                ('author_message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user', verbose_name='автор сообщения')),
            ],
            options={
                'verbose_name': 'собщение',
                'verbose_name_plural': 'собщение',
            },
        ),
    ]
