# Generated by Django 3.2.18 on 2023-04-09 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_auto_20230409_1859'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_task', models.TextField(verbose_name='задача')),
                ('status', models.BooleanField(default=False, verbose_name='статус')),
                ('author_task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_tasks', to='user.user', verbose_name='задание выдал')),
                ('for_user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user', verbose_name='выпоняет')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задача',
            },
        ),
    ]
