# Generated by Django 3.2.18 on 2023-04-08 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.BooleanField(default=False, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_cat',
            field=models.CharField(max_length=100, verbose_name='должность'),
        ),
        migrations.AlterField(
            model_name='message',
            name='author_message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user', verbose_name='автор сообщения'),
        ),
        migrations.AlterField(
            model_name='message',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='время публикации'),
        ),
        migrations.AlterField(
            model_name='message',
            name='text_message',
            field=models.TextField(verbose_name='текст сообщения'),
        ),
        migrations.AlterField(
            model_name='task',
            name='author_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_tasks', to='user.user', verbose_name='задание выдал'),
        ),
        migrations.AlterField(
            model_name='task',
            name='for_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user', verbose_name='выпоняет'),
        ),
        migrations.AlterField(
            model_name='task',
            name='text_task',
            field=models.TextField(verbose_name='задача'),
        ),
        migrations.AlterField(
            model_name='user',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.category', verbose_name='должность'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя сотрудника'),
        ),
    ]
