# Generated by Django 3.2.18 on 2023-04-09 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20230408_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='author_task',
        ),
        migrations.RemoveField(
            model_name='task',
            name='for_user',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'должность', 'verbose_name_plural': 'должность'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудник'},
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
