# Generated by Django 3.2.18 on 2023-04-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20230409_1859'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотруднки'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='category',
        ),
        migrations.AddField(
            model_name='user',
            name='employee',
            field=models.CharField(choices=[('m', 'Менеджер'), ('k', 'Консультант')], default='k', max_length=1),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
